CREATE DATABASE SMART_CITY;

USE SMART_CITY;

SELECT DATABASE(); 

CREATE TABLE ZONE (
    ZONE_ID INT PRIMARY KEY,
    ZONE_NAME VARCHAR(100) NOT NULL UNIQUE
);
DESC ZONE;


CREATE TABLE CITIZEN (
    CITIZEN_ID INT PRIMARY KEY,
    CITIZEN_NAME VARCHAR(100) NOT NULL,
    DATE_OF_BIRTH DATE,
    GENDER VARCHAR(10),
    MOBILE_NUMBER VARCHAR(15) UNIQUE,
    EMAIL VARCHAR(100) UNIQUE,
    AADHAAR_NUMBER VARCHAR(12) UNIQUE,
    ZONE_ID INT,

    CONSTRAINT FK_CITIZEN_ZONE
        FOREIGN KEY (ZONE_ID)
        REFERENCES ZONE(ZONE_ID),

    CONSTRAINT CHK_CITIZEN_GENDER
        CHECK (GENDER IN ('Male','Female','Other'))
);

CREATE TABLE PROPERTY (
    PROPERTY_ID INT PRIMARY KEY,
    CITIZEN_ID INT,
    PROPERTY_TYPE VARCHAR(20),
    PROPERTY_ADDRESS VARCHAR(300),
    PROPERTY_VALUE DECIMAL(15,2),

    CONSTRAINT FK_PROPERTY_CITIZEN
        FOREIGN KEY (CITIZEN_ID)
        REFERENCES CITIZEN(CITIZEN_ID),

    CONSTRAINT CHK_PROPERTY_VALUE
        CHECK (PROPERTY_VALUE > 0),

    CONSTRAINT CHK_PROPERTY_TYPE
        CHECK (PROPERTY_TYPE IN
        ('Residential','Commercial','Industrial'))
);

CREATE TABLE PROPERTY_TAX (
    TAX_ID INT PRIMARY KEY,
    PROPERTY_ID INT,
    TAX_YEAR YEAR,
    TAX_AMOUNT DECIMAL(15,2),
    PAYMENT_STATUS VARCHAR(20),

    CONSTRAINT FK_TAX_PROPERTY
        FOREIGN KEY (PROPERTY_ID)
        REFERENCES PROPERTY(PROPERTY_ID),

    CONSTRAINT CHK_TAX_AMOUNT
        CHECK (TAX_AMOUNT > 0),

    CONSTRAINT CHK_PAYMENT_STATUS
        CHECK (PAYMENT_STATUS IN ('Paid','Pending'))
);

CREATE TABLE WATER_CONNECTION (
    CONNECTION_ID INT PRIMARY KEY,
    PROPERTY_ID INT,
    METER_NUMBER VARCHAR(30) UNIQUE,
    MONTHLY_CONSUMPTION DECIMAL(10,2),
    BILL_AMOUNT DECIMAL(12,2),

    CONSTRAINT FK_WATER_PROPERTY
        FOREIGN KEY (PROPERTY_ID)
        REFERENCES PROPERTY(PROPERTY_ID),

    CONSTRAINT CHK_WATER_CONSUMPTION
        CHECK (MONTHLY_CONSUMPTION >= 0),

    CONSTRAINT CHK_WATER_BILL
        CHECK (BILL_AMOUNT >= 0)
);

CREATE TABLE ELECTRICITY_CONNECTION (
    CONNECTION_ID INT PRIMARY KEY,
    PROPERTY_ID INT,
    METER_NUMBER VARCHAR(30) UNIQUE,
    MONTHLY_UNITS DECIMAL(10,2),
    BILL_AMOUNT DECIMAL(12,2),

    CONSTRAINT FK_ELECTRICITY_PROPERTY
        FOREIGN KEY (PROPERTY_ID)
        REFERENCES PROPERTY(PROPERTY_ID),

    CONSTRAINT CHK_ELECTRICITY_UNITS
        CHECK (MONTHLY_UNITS >= 0),

    CONSTRAINT CHK_ELECTRICITY_BILL
        CHECK (BILL_AMOUNT >= 0)
);

CREATE TABLE WASTE_COLLECTION (
    COLLECTION_ID INT PRIMARY KEY,
    ZONE_ID INT,
    COLLECTION_DATE DATE,
    WASTE_QUANTITY DECIMAL(10,2),

    CONSTRAINT FK_WASTE_ZONE
        FOREIGN KEY (ZONE_ID)
        REFERENCES ZONE(ZONE_ID),

    CONSTRAINT CHK_WASTE_QUANTITY
        CHECK (WASTE_QUANTITY > 0)
);

CREATE TABLE COMPLAINT (
    COMPLAINT_ID INT PRIMARY KEY,
    CITIZEN_ID INT,
    COMPLAINT_TYPE VARCHAR(100),
    COMPLAINT_DESCRIPTION VARCHAR(500),
    COMPLAINT_DATE DATE,
    RESOLUTION_DATE DATE,
    STATUS VARCHAR(20),

    CONSTRAINT FK_COMPLAINT_CITIZEN
        FOREIGN KEY (CITIZEN_ID)
        REFERENCES CITIZEN(CITIZEN_ID),

    CONSTRAINT CHK_COMPLAINT_STATUS
        CHECK (STATUS IN ('Open','In Progress','Resolved'))
);

CREATE TABLE TRAFFIC_VIOLATION (
    VIOLATION_ID INT PRIMARY KEY,
    CITIZEN_ID INT,
    VEHICLE_NUMBER VARCHAR(20),
    VIOLATION_TYPE VARCHAR(100),
    FINE_AMOUNT DECIMAL(10,2),

    CONSTRAINT FK_VIOLATION_CITIZEN
        FOREIGN KEY (CITIZEN_ID)
        REFERENCES CITIZEN(CITIZEN_ID),

    CONSTRAINT CHK_FINE_AMOUNT
        CHECK (FINE_AMOUNT > 0)
);

CREATE TABLE SERVICE_REQUEST (
    REQUEST_ID INT PRIMARY KEY,
    CITIZEN_ID INT,
    SERVICE_TYPE VARCHAR(100),
    REQUEST_DATE DATE,
    REQUEST_STATUS VARCHAR(20),

    CONSTRAINT FK_REQUEST_CITIZEN
        FOREIGN KEY (CITIZEN_ID)
        REFERENCES CITIZEN(CITIZEN_ID),

    CONSTRAINT CHK_REQUEST_STATUS
        CHECK (REQUEST_STATUS IN
        ('Pending','Approved','Rejected','Completed'))
);

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INT PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR(100) NOT NULL,
    DEPARTMENT VARCHAR(100),
    SALARY DECIMAL(12,2),
    MANAGER_ID INT,

    CONSTRAINT CHK_EMPLOYEE_SALARY
        CHECK (SALARY > 0),

    CONSTRAINT FK_EMPLOYEE_MANAGER
        FOREIGN KEY (MANAGER_ID)
        REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

SHOW TABLES;

INSERT INTO ZONE (ZONE_ID, ZONE_NAME) VALUES
(1, 'Central'),
(2, 'North'),
(3, 'South'),
(4, 'East'),
(5, 'West'),
(6, 'North East'),
(7, 'North West'),
(8, 'South East'),
(9, 'South West'),
(10, 'Industrial');

 SELECT * FROM ZONE;
 
 CREATE TABLE NUMBERS (
    N INT PRIMARY KEY
);

INSERT INTO NUMBERS (N)
SELECT a.N + b.N * 10 + 1
FROM
(
    SELECT 0 N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4
    UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9
) a
CROSS JOIN
(
    SELECT 0 N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4
    UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9
) b
WHERE a.N + b.N * 10 + 1 <= 200;

INSERT INTO CITIZEN
(CITIZEN_ID, CITIZEN_NAME, DATE_OF_BIRTH, GENDER,
 MOBILE_NUMBER, EMAIL, AADHAAR_NUMBER, ZONE_ID)

SELECT
    1000 + N,
    CONCAT('Citizen ', N),
    DATE_SUB('2000-01-01', INTERVAL N DAY),
    CASE
        WHEN MOD(N,3) = 0 THEN 'Male'
        WHEN MOD(N,3) = 1 THEN 'Female'
        ELSE 'Other'
    END,
    CONCAT('900000', LPAD(N,6,'0')),
    CONCAT('citizen',N,'@gmail.com'),
    CONCAT('123456',LPAD(N,6,'0')),
    MOD(N-1,10)+1
FROM NUMBERS;

SELECT COUNT(*) AS TOTAL_CITIZENS
FROM CITIZEN;
 
 INSERT INTO PROPERTY
(PROPERTY_ID, CITIZEN_ID, PROPERTY_TYPE, PROPERTY_ADDRESS, PROPERTY_VALUE)

SELECT
    2000 + N,
    1000 + N,
    CASE
        WHEN MOD(N,3) = 0 THEN 'Residential'
        WHEN MOD(N,3) = 1 THEN 'Commercial'
        ELSE 'Industrial'
    END,
    CONCAT(N, ', Smart City Main Road, Zone ', MOD(N-1,10)+1),
    500000 + (N * 25000)
FROM NUMBERS
WHERE N <= 150;

SELECT COUNT(*) FROM PROPERTY;

INSERT INTO PROPERTY_TAX
(TAX_ID, PROPERTY_ID, TAX_YEAR, TAX_AMOUNT, PAYMENT_STATUS)

SELECT
    3000 + N,
    2000 + N,
    2026,
    10000 + (N * 1500),
    CASE
        WHEN MOD(N,4) = 0 THEN 'Pending'
        ELSE 'Paid'
    END
FROM NUMBERS
WHERE N <= 150;

INSERT INTO WATER_CONNECTION
(CONNECTION_ID, PROPERTY_ID, METER_NUMBER,
 MONTHLY_CONSUMPTION, BILL_AMOUNT)

SELECT
    4000 + N,
    2000 + N,
    CONCAT('WM', LPAD(N,5,'0')),
    50 + MOD(N,100),
    300 + (MOD(N,100) * 5)
FROM NUMBERS
WHERE N <= 100;

INSERT INTO ELECTRICITY_CONNECTION
(CONNECTION_ID, PROPERTY_ID, METER_NUMBER,
 MONTHLY_UNITS, BILL_AMOUNT)

SELECT
    5000 + N,
    2000 + N,
    CONCAT('EM', LPAD(N,5,'0')),
    100 + MOD(N,400),
    500 + (MOD(N,400) * 7)
FROM NUMBERS
WHERE N <= 100;

INSERT INTO WASTE_COLLECTION
(COLLECTION_ID, ZONE_ID, COLLECTION_DATE, WASTE_QUANTITY)

SELECT
    6000 + N,
    MOD(N-1,10)+1,
    DATE_SUB('2026-08-01', INTERVAL N DAY),
    100 + MOD(N,200)
FROM NUMBERS
WHERE N <= 100;

INSERT INTO COMPLAINT
(COMPLAINT_ID, CITIZEN_ID, COMPLAINT_TYPE,
 COMPLAINT_DESCRIPTION, COMPLAINT_DATE,
 RESOLUTION_DATE, STATUS)

SELECT
    7000 + N,
    1000 + MOD(N-1,200)+1,

    CASE
        WHEN MOD(N,4) = 0 THEN 'Water'
        WHEN MOD(N,4) = 1 THEN 'Electricity'
        WHEN MOD(N,4) = 2 THEN 'Road'
        ELSE 'Waste'
    END,

    CONCAT('Complaint regarding public service issue ',N),

    DATE_SUB('2026-08-15', INTERVAL N DAY),

    CASE
        WHEN MOD(N,3) = 0
        THEN DATE_SUB('2026-08-15', INTERVAL MOD(N,20) DAY)
        ELSE NULL
    END,

    CASE
        WHEN MOD(N,3) = 0 THEN 'Resolved'
        WHEN MOD(N,3) = 1 THEN 'In Progress'
        ELSE 'Open'
    END

FROM NUMBERS
WHERE N <= 150;

INSERT INTO TRAFFIC_VIOLATION
(VIOLATION_ID, CITIZEN_ID, VEHICLE_NUMBER,
 VIOLATION_TYPE, FINE_AMOUNT)

SELECT
    8000 + N,
    1000 + MOD(N-1,200)+1,
    CONCAT('TN',MOD(N,90)+1,'AB',LPAD(N,4,'0')),

    CASE
        WHEN MOD(N,4) = 0 THEN 'Speeding'
        WHEN MOD(N,4) = 1 THEN 'No Helmet'
        WHEN MOD(N,4) = 2 THEN 'Signal Jump'
        ELSE 'Wrong Parking'
    END,

    500 + MOD(N,5)*500

FROM NUMBERS
WHERE N <= 100;

INSERT INTO SERVICE_REQUEST
(REQUEST_ID, CITIZEN_ID, SERVICE_TYPE,
 REQUEST_DATE, REQUEST_STATUS)

SELECT
    9000 + N,
    1000 + MOD(N-1,200)+1,

    CASE
        WHEN MOD(N,4) = 0 THEN 'Birth Certificate'
        WHEN MOD(N,4) = 1 THEN 'Property Registration'
        WHEN MOD(N,4) = 2 THEN 'Water Connection'
        ELSE 'Trade License'
    END,

    DATE_SUB('2026-08-15', INTERVAL N DAY),

    CASE
        WHEN MOD(N,4) = 0 THEN 'Pending'
        WHEN MOD(N,4) = 1 THEN 'Approved'
        WHEN MOD(N,4) = 2 THEN 'Rejected'
        ELSE 'Completed'
    END

FROM NUMBERS
WHERE N <= 150;

INSERT INTO EMPLOYEE
(EMPLOYEE_ID, EMPLOYEE_NAME, DEPARTMENT, SALARY, MANAGER_ID)

SELECT
    10000 + N,
    CONCAT('Employee ',N),

    CASE
        WHEN MOD(N,5) = 0 THEN 'Revenue'
        WHEN MOD(N,5) = 1 THEN 'Water'
        WHEN MOD(N,5) = 2 THEN 'Electricity'
        WHEN MOD(N,5) = 3 THEN 'Transport'
        ELSE 'Waste Management'
    END,

    30000 + (N * 1000),

    NULL

FROM NUMBERS
WHERE N <= 50;

UPDATE EMPLOYEE
SET MANAGER_ID = 10001
WHERE EMPLOYEE_ID BETWEEN 10002 AND 10010;

UPDATE EMPLOYEE
SET MANAGER_ID = 10011
WHERE EMPLOYEE_ID BETWEEN 10012 AND 10020;

UPDATE EMPLOYEE
SET MANAGER_ID = 10021
WHERE EMPLOYEE_ID BETWEEN 10022 AND 10030;

UPDATE EMPLOYEE
SET MANAGER_ID = 10031
WHERE EMPLOYEE_ID BETWEEN 10032 AND 10040;

UPDATE EMPLOYEE
SET MANAGER_ID = 10041
WHERE EMPLOYEE_ID BETWEEN 10042 AND 10050;

SELECT 'ZONE' AS TABLE_NAME, COUNT(*) AS RECORDS FROM ZONE
UNION ALL
SELECT 'CITIZEN', COUNT(*) FROM CITIZEN
UNION ALL
SELECT 'PROPERTY', COUNT(*) FROM PROPERTY
UNION ALL
SELECT 'PROPERTY_TAX', COUNT(*) FROM PROPERTY_TAX
UNION ALL
SELECT 'WATER_CONNECTION', COUNT(*) FROM WATER_CONNECTION
UNION ALL
SELECT 'ELECTRICITY_CONNECTION', COUNT(*) FROM ELECTRICITY_CONNECTION
UNION ALL
SELECT 'WASTE_COLLECTION', COUNT(*) FROM WASTE_COLLECTION
UNION ALL
SELECT 'COMPLAINT', COUNT(*) FROM COMPLAINT
UNION ALL
SELECT 'TRAFFIC_VIOLATION', COUNT(*) FROM TRAFFIC_VIOLATION
UNION ALL
SELECT 'SERVICE_REQUEST', COUNT(*) FROM SERVICE_REQUEST
UNION ALL
SELECT 'EMPLOYEE', COUNT(*) FROM EMPLOYEE;

SELECT CITIZEN_NAME,
       UPPER(CITIZEN_NAME) AS UPPERCASE_NAME
FROM CITIZEN;

SELECT ZONE_NAME,
       LEFT(ZONE_NAME, 5) AS FIRST_5_CHARACTERS
FROM ZONE;

SELECT EMPLOYEE_NAME,
       LOWER(EMPLOYEE_NAME) AS LOWERCASE_NAME
FROM EMPLOYEE;

SELECT COMPLAINT_TYPE,
       LENGTH(COMPLAINT_TYPE) AS TYPE_LENGTH
FROM COMPLAINT;

SELECT REQUEST_ID,
       REQUEST_DATE,
       MONTH(REQUEST_DATE) AS REQUEST_MONTH
FROM SERVICE_REQUEST;


SELECT MAX(PROPERTY_VALUE) AS HIGHEST_PROPERTY_VALUE
FROM PROPERTY;

SELECT MIN(PROPERTY_VALUE) AS LOWEST_PROPERTY_VALUE
FROM PROPERTY;

SELECT AVG(PROPERTY_VALUE) AS AVERAGE_PROPERTY_VALUE
FROM PROPERTY;

SELECT SUM(TAX_AMOUNT) AS TOTAL_TAX_COLLECTED
FROM PROPERTY_TAX
WHERE PAYMENT_STATUS = 'Paid';

SELECT COUNT(*) AS TOTAL_CITIZENS
FROM CITIZEN;

SELECT COUNT(*) AS TOTAL_COMPLAINTS
FROM COMPLAINT;

SELECT Z.ZONE_NAME,
       COUNT(C.CITIZEN_ID) AS CITIZEN_COUNT
FROM ZONE Z
LEFT JOIN CITIZEN C
ON Z.ZONE_ID = C.ZONE_ID
GROUP BY Z.ZONE_ID, Z.ZONE_NAME;

SELECT Z.ZONE_NAME,
       COUNT(P.PROPERTY_ID) AS PROPERTY_COUNT
FROM ZONE Z
JOIN CITIZEN C
ON Z.ZONE_ID = C.ZONE_ID
JOIN PROPERTY P
ON C.CITIZEN_ID = P.CITIZEN_ID
GROUP BY Z.ZONE_ID, Z.ZONE_NAME;

SELECT COMPLAINT_TYPE,
       COUNT(*) AS COMPLAINT_COUNT
FROM COMPLAINT
GROUP BY COMPLAINT_TYPE;

SELECT SERVICE_TYPE,
       COUNT(*) AS REQUEST_COUNT
FROM SERVICE_REQUEST
GROUP BY SERVICE_TYPE;

SELECT DEPARTMENT,
       COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEE
GROUP BY DEPARTMENT;

SELECT Z.ZONE_NAME,
       COUNT(C.CITIZEN_ID) AS CITIZEN_COUNT
FROM ZONE Z
JOIN CITIZEN C
ON Z.ZONE_ID = C.ZONE_ID
GROUP BY Z.ZONE_ID, Z.ZONE_NAME
HAVING COUNT(C.CITIZEN_ID) > 20;

SELECT Z.ZONE_NAME,
       SUM(PT.TAX_AMOUNT) AS TOTAL_TAX
FROM ZONE Z
JOIN CITIZEN C
ON Z.ZONE_ID = C.ZONE_ID
JOIN PROPERTY P
ON C.CITIZEN_ID = P.CITIZEN_ID
JOIN PROPERTY_TAX PT
ON P.PROPERTY_ID = PT.PROPERTY_ID
WHERE PT.PAYMENT_STATUS = 'Paid'
GROUP BY Z.ZONE_ID, Z.ZONE_NAME
HAVING SUM(PT.TAX_AMOUNT) > 1000000;

SELECT COMPLAINT_TYPE,
       COUNT(*) AS COMPLAINT_COUNT
FROM COMPLAINT
GROUP BY COMPLAINT_TYPE
HAVING COUNT(*) > 10;

SELECT
    C.CITIZEN_NAME,
    Z.ZONE_NAME,
    P.PROPERTY_TYPE,
    P.PROPERTY_VALUE
FROM CITIZEN C
INNER JOIN ZONE Z
ON C.ZONE_ID = Z.ZONE_ID
INNER JOIN PROPERTY P
ON C.CITIZEN_ID = P.CITIZEN_ID;

SELECT
    C.CITIZEN_ID,
    C.CITIZEN_NAME,
    CP.COMPLAINT_ID,
    CP.COMPLAINT_TYPE,
    CP.STATUS
FROM CITIZEN C
LEFT JOIN COMPLAINT CP
ON C.CITIZEN_ID = CP.CITIZEN_ID;

SELECT
    P.PROPERTY_ID,
    P.PROPERTY_TYPE,
    P.PROPERTY_VALUE,
    PT.TAX_ID,
    PT.TAX_AMOUNT,
    PT.PAYMENT_STATUS
FROM PROPERTY_TAX PT
RIGHT JOIN PROPERTY P
ON PT.PROPERTY_ID = P.PROPERTY_ID;

SELECT
    C.CITIZEN_ID,
    C.CITIZEN_NAME,
    CP.COMPLAINT_ID,
    CP.COMPLAINT_TYPE,
    CP.STATUS
FROM CITIZEN C
LEFT JOIN COMPLAINT CP
ON C.CITIZEN_ID = CP.CITIZEN_ID

UNION

SELECT
    C.CITIZEN_ID,
    C.CITIZEN_NAME,
    CP.COMPLAINT_ID,
    CP.COMPLAINT_TYPE,
    CP.STATUS
FROM CITIZEN C
RIGHT JOIN COMPLAINT CP
ON C.CITIZEN_ID = CP.CITIZEN_ID;

SELECT
    E.EMPLOYEE_NAME AS EMPLOYEE_NAME,
    M.EMPLOYEE_NAME AS MANAGER_NAME
FROM EMPLOYEE E
LEFT JOIN EMPLOYEE M
ON E.MANAGER_ID = M.EMPLOYEE_ID;

CREATE TABLE DEPARTMENT (
    DEPARTMENT_NAME VARCHAR(100) PRIMARY KEY
);

INSERT INTO DEPARTMENT VALUES
('Revenue'),
('Water'),
('Electricity'),
('Transport'),
('Waste Management');

SELECT
    Z.ZONE_NAME,
    D.DEPARTMENT_NAME
FROM ZONE Z
CROSS JOIN DEPARTMENT D;

SELECT
    C.CITIZEN_NAME,
    Z.ZONE_NAME,
    P.PROPERTY_TYPE,
    P.PROPERTY_ADDRESS,
    P.PROPERTY_VALUE,
    PT.TAX_AMOUNT,
    CP.STATUS AS COMPLAINT_STATUS,
    SR.REQUEST_STATUS
FROM CITIZEN C
JOIN ZONE Z
ON C.ZONE_ID = Z.ZONE_ID
LEFT JOIN PROPERTY P
ON C.CITIZEN_ID = P.CITIZEN_ID
LEFT JOIN PROPERTY_TAX PT
ON P.PROPERTY_ID = PT.PROPERTY_ID
LEFT JOIN COMPLAINT CP
ON C.CITIZEN_ID = CP.CITIZEN_ID
LEFT JOIN SERVICE_REQUEST SR
ON C.CITIZEN_ID = SR.CITIZEN_ID;

SELECT DISTINCT
    C.CITIZEN_ID,
    C.CITIZEN_NAME
FROM CITIZEN C
JOIN PROPERTY P
ON C.CITIZEN_ID = P.CITIZEN_ID
WHERE P.PROPERTY_VALUE >
(
    SELECT AVG(PROPERTY_VALUE)
    FROM PROPERTY
);

SELECT
    Z.ZONE_NAME,
    SUM(PT.TAX_AMOUNT) AS TOTAL_TAX
FROM ZONE Z
JOIN CITIZEN C
ON Z.ZONE_ID = C.ZONE_ID
JOIN PROPERTY P
ON C.CITIZEN_ID = P.CITIZEN_ID
JOIN PROPERTY_TAX PT
ON P.PROPERTY_ID = PT.PROPERTY_ID
WHERE PT.PAYMENT_STATUS = 'Paid'
GROUP BY Z.ZONE_ID, Z.ZONE_NAME
HAVING SUM(PT.TAX_AMOUNT) =
(
    SELECT MAX(TOTAL_TAX)
    FROM
    (
        SELECT SUM(PT2.TAX_AMOUNT) AS TOTAL_TAX
        FROM PROPERTY_TAX PT2
        WHERE PT2.PAYMENT_STATUS = 'Paid'
        GROUP BY PT2.PROPERTY_ID
    ) X
);

SELECT DISTINCT
    C.CITIZEN_NAME,
    PT.TAX_AMOUNT
FROM CITIZEN C
JOIN PROPERTY P
ON C.CITIZEN_ID = P.CITIZEN_ID
JOIN PROPERTY_TAX PT
ON P.PROPERTY_ID = PT.PROPERTY_ID
WHERE PT.TAX_AMOUNT =
(
    SELECT MAX(TAX_AMOUNT)
    FROM PROPERTY_TAX
);

SELECT DISTINCT
    C.CITIZEN_ID,
    C.CITIZEN_NAME
FROM CITIZEN C
WHERE C.CITIZEN_ID IN
(
    SELECT P.CITIZEN_ID
    FROM PROPERTY P
    WHERE P.PROPERTY_TYPE IN
    ('Residential','Commercial')
);

SELECT
    P.PROPERTY_ID,
    P.PROPERTY_VALUE
FROM PROPERTY P
WHERE P.PROPERTY_VALUE >
ANY
(
    SELECT P2.PROPERTY_VALUE
    FROM PROPERTY P2
    JOIN CITIZEN C2
    ON P2.CITIZEN_ID = C2.CITIZEN_ID
    WHERE C2.ZONE_ID = 1
);

SELECT
    P.PROPERTY_ID,
    P.PROPERTY_VALUE
FROM PROPERTY P
WHERE P.PROPERTY_VALUE >
ALL
(
    SELECT P2.PROPERTY_VALUE
    FROM PROPERTY P2
    JOIN CITIZEN C2
    ON P2.CITIZEN_ID = C2.CITIZEN_ID
    WHERE C2.ZONE_ID = 2
);

SELECT
    C.CITIZEN_ID,
    C.CITIZEN_NAME,
    C.ZONE_ID
FROM CITIZEN C
WHERE C.ZONE_ID =
(
    SELECT ZONE_ID
    FROM
    (
        SELECT C2.ZONE_ID,
               SUM(PT.TAX_AMOUNT) AS TOTAL_TAX
        FROM CITIZEN C2
        JOIN PROPERTY P
        ON C2.CITIZEN_ID = P.CITIZEN_ID
        JOIN PROPERTY_TAX PT
        ON P.PROPERTY_ID = PT.PROPERTY_ID
        WHERE PT.PAYMENT_STATUS = 'Paid'
        GROUP BY C2.ZONE_ID
        ORDER BY TOTAL_TAX DESC
        LIMIT 1
    ) X
);

SELECT
    CP.COMPLAINT_ID,
    CP.COMPLAINT_TYPE,
    CP.STATUS,
    C.CITIZEN_NAME,
    C.ZONE_ID
FROM COMPLAINT CP
JOIN CITIZEN C
ON CP.CITIZEN_ID = C.CITIZEN_ID
WHERE C.ZONE_ID =
(
    SELECT ZONE_ID
    FROM
    (
        SELECT C2.ZONE_ID,
               COUNT(*) AS TOTAL_COMPLAINTS
        FROM COMPLAINT CP2
        JOIN CITIZEN C2
        ON CP2.CITIZEN_ID = C2.CITIZEN_ID
        GROUP BY C2.ZONE_ID
        ORDER BY TOTAL_COMPLAINTS DESC
        LIMIT 1
    ) X
);

SELECT DISTINCT
    C.CITIZEN_NAME,
    PT.TAX_AMOUNT,
    C.ZONE_ID
FROM CITIZEN C
JOIN PROPERTY P
ON C.CITIZEN_ID = P.CITIZEN_ID
JOIN PROPERTY_TAX PT
ON P.PROPERTY_ID = PT.PROPERTY_ID
WHERE PT.TAX_AMOUNT >
(
    SELECT AVG(PT2.TAX_AMOUNT)
    FROM PROPERTY_TAX PT2
    JOIN PROPERTY P2
    ON PT2.PROPERTY_ID = P2.PROPERTY_ID
    JOIN CITIZEN C2
    ON P2.CITIZEN_ID = C2.CITIZEN_ID
    WHERE C2.ZONE_ID = C.ZONE_ID
);

SELECT
    E.EMPLOYEE_NAME,
    E.DEPARTMENT,
    E.SALARY
FROM EMPLOYEE E
WHERE E.SALARY >
(
    SELECT AVG(E2.SALARY)
    FROM EMPLOYEE E2
    WHERE E2.DEPARTMENT = E.DEPARTMENT
);

SELECT
    C.CITIZEN_ID,
    C.CITIZEN_NAME
FROM CITIZEN C
WHERE EXISTS
(
    SELECT 1
    FROM COMPLAINT CP
    WHERE CP.CITIZEN_ID = C.CITIZEN_ID
);

SELECT
    C.CITIZEN_ID,
    C.CITIZEN_NAME
FROM CITIZEN C
WHERE EXISTS
(
    SELECT 1
    FROM SERVICE_REQUEST SR
    WHERE SR.CITIZEN_ID = C.CITIZEN_ID
);

SELECT
    Z.ZONE_ID,
    Z.ZONE_NAME
FROM ZONE Z
WHERE EXISTS
(
    SELECT 1
    FROM CITIZEN C
    JOIN PROPERTY P
    ON C.CITIZEN_ID = P.CITIZEN_ID
    WHERE C.ZONE_ID = Z.ZONE_ID
);

SELECT
    C.CITIZEN_ID,
    C.CITIZEN_NAME
FROM CITIZEN C
WHERE NOT EXISTS
(
    SELECT 1
    FROM COMPLAINT CP
    WHERE CP.CITIZEN_ID = C.CITIZEN_ID
);

SELECT
    P.PROPERTY_ID,
    P.PROPERTY_TYPE
FROM PROPERTY P
WHERE NOT EXISTS
(
    SELECT 1
    FROM PROPERTY_TAX PT
    WHERE PT.PROPERTY_ID = P.PROPERTY_ID
);

SELECT
    Z.ZONE_ID,
    Z.ZONE_NAME
FROM ZONE Z
WHERE NOT EXISTS
(
    SELECT 1
    FROM CITIZEN C
    JOIN SERVICE_REQUEST SR
    ON C.CITIZEN_ID = SR.CITIZEN_ID
    WHERE C.ZONE_ID = Z.ZONE_ID
);

CREATE TABLE TAX_PAYERS AS
SELECT DISTINCT CITIZEN_ID
FROM CITIZEN C
WHERE EXISTS (
    SELECT 1
    FROM PROPERTY P
    JOIN PROPERTY_TAX PT
    ON P.PROPERTY_ID = PT.PROPERTY_ID
    WHERE P.CITIZEN_ID = C.CITIZEN_ID
    AND PT.PAYMENT_STATUS = 'Paid'
);

SELECT * FROM TAX_PAYERS;

CREATE TABLE SERVICE_USERS AS
SELECT DISTINCT CITIZEN_ID
FROM SERVICE_REQUEST;

SELECT * FROM SERVICE_USERS;

SELECT CITIZEN_ID
FROM TAX_PAYERS

UNION

SELECT CITIZEN_ID
FROM SERVICE_USERS;

SELECT CITIZEN_ID
FROM TAX_PAYERS

UNION ALL

SELECT CITIZEN_ID
FROM SERVICE_USERS;


SELECT CITIZEN_ID
FROM TAX_PAYERS

EXCEPT

SELECT CITIZEN_ID
FROM SERVICE_USERS;

CREATE VIEW CITIZEN_PROFILE_VIEW AS
SELECT
    C.CITIZEN_ID,
    C.CITIZEN_NAME,
    Z.ZONE_NAME,
    P.PROPERTY_TYPE,
    P.PROPERTY_ADDRESS,
    P.PROPERTY_VALUE
FROM CITIZEN C
JOIN ZONE Z
ON C.ZONE_ID = Z.ZONE_ID
LEFT JOIN PROPERTY P
ON C.CITIZEN_ID = P.CITIZEN_ID;

SELECT * FROM CITIZEN_PROFILE_VIEW;

CREATE VIEW TAX_COLLECTION_VIEW AS
SELECT
    Z.ZONE_NAME,
    SUM(PT.TAX_AMOUNT) AS TOTAL_TAX_COLLECTED
FROM ZONE Z
JOIN CITIZEN C
ON Z.ZONE_ID = C.ZONE_ID
JOIN PROPERTY P
ON C.CITIZEN_ID = P.CITIZEN_ID
JOIN PROPERTY_TAX PT
ON P.PROPERTY_ID = PT.PROPERTY_ID
WHERE PT.PAYMENT_STATUS = 'Paid'
GROUP BY Z.ZONE_ID, Z.ZONE_NAME;

SELECT * FROM TAX_COLLECTION_VIEW;

CREATE VIEW COMPLAINT_STATUS_VIEW AS
SELECT
    C.CITIZEN_NAME,
    CP.COMPLAINT_TYPE,
    CP.STATUS AS COMPLAINT_STATUS
FROM CITIZEN C
JOIN COMPLAINT CP
ON C.CITIZEN_ID = CP.CITIZEN_ID;

SELECT * FROM COMPLAINT_STATUS_VIEW;

CREATE INDEX IDX_CITIZEN_NAME
ON CITIZEN(CITIZEN_NAME);

CREATE UNIQUE INDEX IDX_MOBILE
ON CITIZEN(MOBILE_NUMBER);

CREATE INDEX IDX_PROPERTY_ID
ON PROPERTY_TAX(PROPERTY_ID);

CREATE INDEX IDX_COMPLAINT_DATE
ON COMPLAINT(COMPLAINT_DATE);

SHOW INDEX FROM CITIZEN;

SHOW TABLES;

SELECT *
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SMART_CITY';

SELECT
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_KEY
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SMART_CITY'
ORDER BY TABLE_NAME, ORDINAL_POSITION;

SELECT
    TABLE_NAME,
    COLUMN_NAME,
    CONSTRAINT_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE CONSTRAINT_SCHEMA = 'SMART_CITY'
AND REFERENCED_TABLE_NAME IS NOT NULL;

SELECT
    CITIZEN_NAME,
    DATE_OF_BIRTH,
    TIMESTAMPDIFF(
        YEAR,
        DATE_OF_BIRTH,
        CURDATE()
    ) AS AGE
FROM CITIZEN;

SELECT
    COMPLAINT_ID,
    COMPLAINT_DATE,
    RESOLUTION_DATE,
    DATEDIFF(
        RESOLUTION_DATE,
        COMPLAINT_DATE
    ) AS RESOLUTION_DAYS
FROM COMPLAINT
WHERE STATUS = 'Resolved';

SELECT
    YEAR(REQUEST_DATE) AS REQUEST_YEAR,
    MONTH(REQUEST_DATE) AS REQUEST_MONTH,
    COUNT(*) AS TOTAL_REQUESTS
FROM SERVICE_REQUEST
GROUP BY
    YEAR(REQUEST_DATE),
    MONTH(REQUEST_DATE)
ORDER BY
    REQUEST_YEAR,
    REQUEST_MONTH;
    
    SELECT *
FROM CITIZEN
WHERE CITIZEN_NAME REGEXP '^A';

SELECT
    CITIZEN_ID,
    AADHAAR_NUMBER
FROM CITIZEN
WHERE AADHAAR_NUMBER REGEXP '^[0-9]{12}$';

SELECT
    CITIZEN_NAME,
    EMAIL
FROM CITIZEN
WHERE EMAIL REGEXP '@gmail\\.com$';

SELECT
    PROPERTY_ADDRESS,
    REGEXP_SUBSTR(
        PROPERTY_ADDRESS,
        '^[0-9]+'
    ) AS HOUSE_NUMBER
FROM PROPERTY;

SELECT
    COMPLAINT_DESCRIPTION,
    REGEXP_REPLACE(
        COMPLAINT_DESCRIPTION,
        '[^a-zA-Z0-9 ]',
        ''
    ) AS CLEAN_DESCRIPTION
FROM COMPLAINT;

SELECT
    Z.ZONE_NAME,
    SUM(PT.TAX_AMOUNT) AS TOTAL_TAX
FROM ZONE Z
JOIN CITIZEN C
ON Z.ZONE_ID = C.ZONE_ID
JOIN PROPERTY P
ON C.CITIZEN_ID = P.CITIZEN_ID
JOIN PROPERTY_TAX PT
ON P.PROPERTY_ID = PT.PROPERTY_ID
WHERE PT.PAYMENT_STATUS = 'Paid'
GROUP BY Z.ZONE_ID, Z.ZONE_NAME
ORDER BY TOTAL_TAX DESC
LIMIT 10;

SELECT
    Z.ZONE_NAME,
    COUNT(C.CITIZEN_ID) AS TOTAL_CITIZENS
FROM ZONE Z
LEFT JOIN CITIZEN C
ON Z.ZONE_ID = C.ZONE_ID
GROUP BY Z.ZONE_ID, Z.ZONE_NAME
ORDER BY TOTAL_CITIZENS DESC;

SELECT
    STATUS,
    COUNT(*) AS TOTAL_COMPLAINTS
FROM COMPLAINT
GROUP BY STATUS;

SELECT
    STATUS,
    COUNT(*) AS TOTAL_COMPLAINTS,
    ROUND(
        COUNT(*) * 100.0 /
        (SELECT COUNT(*) FROM COMPLAINT),
        2
    ) AS PERCENTAGE
FROM COMPLAINT
GROUP BY STATUS;

SELECT
    'Water' AS UTILITY,
    SUM(MONTHLY_CONSUMPTION) AS TOTAL_CONSUMPTION
FROM WATER_CONNECTION

UNION ALL

SELECT
    'Electricity',
    SUM(MONTHLY_UNITS)
FROM ELECTRICITY_CONNECTION;

SELECT
    VIOLATION_TYPE,
    COUNT(*) AS TOTAL_VIOLATIONS,
    SUM(FINE_AMOUNT) AS TOTAL_FINE
FROM TRAFFIC_VIOLATION
GROUP BY VIOLATION_TYPE
ORDER BY TOTAL_FINE DESC;

SELECT
    REQUEST_STATUS,
    COUNT(*) AS TOTAL_REQUESTS
FROM SERVICE_REQUEST
GROUP BY REQUEST_STATUS
ORDER BY TOTAL_REQUESTS DESC;

SELECT
    Z.ZONE_NAME,
    SUM(W.MONTHLY_CONSUMPTION) AS TOTAL_WATER_CONSUMPTION,
    AVG(W.MONTHLY_CONSUMPTION) AS AVG_WATER_CONSUMPTION,
    SUM(W.BILL_AMOUNT) AS TOTAL_WATER_BILL
FROM WATER_CONNECTION W
JOIN PROPERTY P
ON W.PROPERTY_ID = P.PROPERTY_ID
JOIN CITIZEN C
ON P.CITIZEN_ID = C.CITIZEN_ID
JOIN ZONE Z
ON C.ZONE_ID = Z.ZONE_ID
GROUP BY Z.ZONE_ID, Z.ZONE_NAME
ORDER BY TOTAL_WATER_CONSUMPTION DESC;

SELECT
    Z.ZONE_NAME,
    SUM(E.MONTHLY_UNITS) AS TOTAL_UNITS,
    AVG(E.MONTHLY_UNITS) AS AVG_UNITS,
    SUM(E.BILL_AMOUNT) AS TOTAL_ELECTRICITY_BILL
FROM ELECTRICITY_CONNECTION E
JOIN PROPERTY P
ON E.PROPERTY_ID = P.PROPERTY_ID
JOIN CITIZEN C
ON P.CITIZEN_ID = C.CITIZEN_ID
JOIN ZONE Z
ON C.ZONE_ID = Z.ZONE_ID
GROUP BY Z.ZONE_ID, Z.ZONE_NAME
ORDER BY TOTAL_UNITS DESC;

SELECT
    Z.ZONE_NAME,
    COUNT(W.COLLECTION_ID) AS COLLECTIONS,
    SUM(W.WASTE_QUANTITY) AS TOTAL_WASTE,
    AVG(W.WASTE_QUANTITY) AS AVG_WASTE_PER_COLLECTION
FROM ZONE Z
LEFT JOIN WASTE_COLLECTION W
ON Z.ZONE_ID = W.ZONE_ID
GROUP BY Z.ZONE_ID, Z.ZONE_NAME
ORDER BY TOTAL_WASTE DESC;

SELECT
    'Property Tax' AS REVENUE_SOURCE,
    SUM(TAX_AMOUNT) AS TOTAL_REVENUE
FROM PROPERTY_TAX
WHERE PAYMENT_STATUS = 'Paid'

UNION ALL

SELECT
    'Traffic Fines',
    SUM(FINE_AMOUNT)
FROM TRAFFIC_VIOLATION

UNION ALL

SELECT
    'Water Bills',
    SUM(BILL_AMOUNT)
FROM WATER_CONNECTION

UNION ALL

SELECT
    'Electricity Bills',
    SUM(BILL_AMOUNT)
FROM ELECTRICITY_CONNECTION;

SELECT
    (
        (SELECT COALESCE(SUM(TAX_AMOUNT),0)
         FROM PROPERTY_TAX
         WHERE PAYMENT_STATUS = 'Paid')

        +

        (SELECT COALESCE(SUM(FINE_AMOUNT),0)
         FROM TRAFFIC_VIOLATION)

        +

        (SELECT COALESCE(SUM(BILL_AMOUNT),0)
         FROM WATER_CONNECTION)

        +

        (SELECT COALESCE(SUM(BILL_AMOUNT),0)
         FROM ELECTRICITY_CONNECTION)
    ) AS TOTAL_CITY_REVENUE;
    
    SELECT COUNT(*) FROM ZONE;
SELECT COUNT(*) FROM CITIZEN;
SELECT COUNT(*) FROM PROPERTY;
SELECT COUNT(*) FROM PROPERTY_TAX;
SELECT COUNT(*) FROM WATER_CONNECTION;
SELECT COUNT(*) FROM ELECTRICITY_CONNECTION;
SELECT COUNT(*) FROM WASTE_COLLECTION;
SELECT COUNT(*) FROM COMPLAINT;
SELECT COUNT(*) FROM TRAFFIC_VIOLATION;
SELECT COUNT(*) FROM SERVICE_REQUEST;
SELECT COUNT(*) FROM EMPLOYEE;

SHOW FULL TABLES;